# Generated by Django 3.2.3 on 2021-05-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('F', 'Funny'), ('I', 'Insprational'), ('L', 'Love'), ('A', 'Advice')], default='F', max_length=1)),
                ('quote', models.ManyToManyField(blank=True, to='main_app.Quote')),
            ],
        ),
    ]
