# Generated by Django 3.2.3 on 2021-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210527_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[(1, 'Funny'), (2, 'Insprational'), (3, 'Life'), (4, 'Advice'), (5, 'Personal Development'), (6, 'Rated-RRRRR')], default=1, max_length=1),
        ),
    ]
