# Generated by Django 3.2.3 on 2021-05-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('F', 'Funny'), ('I', 'Insprational'), ('L', 'Life'), ('A', 'Advice'), ('P', 'Personal Development'), ('R', 'Rated-RRRRR')], default='F', max_length=1),
        ),
    ]
